### ISSUE TITLE
Option to load in custom ca or ignore tls on operator/installer

### ISSUE THREAD

**Issue by Aureliolo** [glasskube/glasskube#1025]
**Is your feature request related to a problem? Please describe.**
Currently in our infrastructure, we have SSL inspection on the Firewall level. 

Hence all systems internally need to either have the CA trusted of our network team. Or ignore TLS errors in the worst case. 

**Describe the solution you'd like**
Preferably I would be able to load my own ca certs into the operator and have it trust them. (the underlying nodes of k8s all trust them already ofc) or worst case to have it ignore TLS issues. But would strongly prefer the first option to not have to worry in terms of security.

**Comment by kosmoz** [comment]
Hi @Aureliolo, thank you for raising this issue!

Using custom TLS certificates for the operator webhook is currently not supported by the CLI `bootstrap` workflow. That's what you mean right?

Do you have a suggestion what this might look like in the CLI? Or do you know of an example for an application that supports this?

Since I don't know how you usually obtain such a certificate using your internal PKI, I can't give you specific advice, but you could try running `glasskube bootstrap --dry-run -o yaml > glasskube.yaml`, customize the generated manifest as necessary and then use `kubectl apply` to install them.

**Comment by Aureliolo** [comment]
Hi Kosmoz, 

Thank you for your reply! 

This is the error I get:

```
> .\glasskube.exe serve
glasskube UI is available at http://localhost:8580
An error occurred installing headlamp: Internal error occurred: failed calling webhook "vclusterpackage.kb.io": failed to call webhook: Post "https://glasskube-webhook-service.glasskube-system.svc:443/validate-packages-glasskube-dev-v1alpha1-clusterpackage?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "glasskube.dev")
```
So basically when the operator/webhook server/container(haven't looked too deep into the architecture yet of glasskube) tries to connect out. 

We use for example AWX for our ansible automations and there we customise the helm value chart to include the ca cert of our network operations so that it trust it: https://github.com/ansible/awx-operator/blob/devel/.helm/starter/README.md#certificate-authority-secret-configuration

Basically we would need a way to make the glasskube stack aware it needs to trust additional certs when connecting out. Which I think isn't toooo uncommon in an enterprise environment. 

I haven't yet looked to much into what the easiest way would be for glasskube as not yet to familiar with its architecture, but gonna have a look in coming days if I get time.

**Comment by kosmoz** [comment]
Glasskube doesn't need any certificates internally. The CLI doesn't communicate with the operator directly, only with the Kubernetes API. 

The error you observe happens when the Kubernetes API server tries to call the operators validation webhook as a result of the CLI trying to create a `ClusterPackage` resource. Kubernetes only sends requests to validating webhooks via HTTPS, thus requiring a TLS certificate. 

By default, Glasskube includes a CronJob that creates a certificate using a self-signed CA for this purpose in the `glasskube-webhook-tls` secret. The certificate should be valid for the following DNS names: 
1. `glasskube-webhook-service`
2. `glasskube-webhook-service.glasskube-system`
3. `glasskube-webhook-service.glasskube-system.svc`

The CA created for this purpose is also referenced in the relevant `ValidatingWebhookConfiguration`.

So, if you want to provide your own certificate you will have to:
1. Delete the `glasskube-webhook-cert` `CronJob` and the `glasskube-webhook-cert-init` `Job`
6. Update the `glasskube-controller-manager` `Depolyment` so that it uses your certificate 
   OR 
   Create or update the `glasskube-webhook-tls` `Secret` to contain your certificate
7. Update the `glasskube-validating-webhook-configuration` `ValidatingWebhookConfiguration` to contain the certificate of the CA used to create the certificate.

Please let us know if you have any further questions.
