### ISSUE TITLE
CLI update check shows wrong version for PackageOperator

### ISSUE THREAD

**Issue by botchk** [glasskube/glasskube#1121]
**Describe the bug**
When running the update check with the CLI, the new version for the package operator is shown as the version of the locally used CLI.

**To Reproduce**
1. Run `glasskube version --skip-update-check=false` 
2. Newest version for the PackageOperator is shown as `dev` instead of `0.17.0`
```
📣 A newer version of Glasskube is available: dev → 0.17.0
📘 Release notes: https://github.com/glasskube/glasskube/releases/tag/v0.17.0

❗ Glasskube PackageOperator needs to be updated: 0.16.0 -> dev
💡 Please run `glasskube bootstrap` again to update Glasskube PackageOperator
```

**Expected behavior**
The newest version for glasskube should be shown. Same as for the CLI.
`❗ Glasskube PackageOperator needs to be updated: 0.16.0 -> 0.17.0`

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: v1.29.2
 - Provider: kind

**Glasskube Info (please complete the following information):**
 - Package Operator version: v0.16.0
 - CLI version: dev (https://github.com/glasskube/glasskube/commit/31cfe95d2088d3c0166e04b000af4f5a315db03d)

**Comment by kosmoz** [comment]
This is only an issue in dev mode, because the default version string ("dev") can not be parsed as semver. In a released version, the CLI shows a warning if the operator version differs from the installed CLI version. The operator version warning should not suggest installing a newer version than the installed CLI, because this can lead to different issues. But I agree that having the warning in dev mode is incorrect and can be confusing, so I would suggest replacing the operator version warning with a simple message like "Glasskube CLI version is dev but the operator version is 0.16.0" if the CLI version is "dev" and the operator version is not empty.

What do you think @botchk?

**Comment by botchk** [comment]
If not installing a newer version than the CLI is intended, yes I think the proposal is good 👍

**Comment by Aryakoste** [comment]
Hello @pmig @kosmoz I would like to work on this issue.
