### ISSUE TITLE
Refresh installation status on the UI automatically

### ISSUE THREAD

**Issue by mhandler86** [glasskube/glasskube#164]
The package overview page should update itself when a package installation is finished, instead of having the user manually refresh it.

**Comment by aatbip** [comment]
I want to work on this as well.

**Comment by pmig** [comment]
@aatbip survey thanks!

**Comment by christophenne** [comment]
@aatbip @pmig please keep in mind that right now the UI is still at the very beginning, and tech stack is not 100% where we want it yet, and we took some shortcuts (which you probably already stumbled upon). I wrote some things down in #126 - I think we need to decide on some things before we go much deeper into feature development on the UI. 

so from the issues you'd like to work on, I think #172 might be the most useful, because even if we add/change something to the stack, at least the html will survive. 

just my opinion and a little heads-up before you go in too deep. we can probably give more info on monday and stay in sync :)

**Comment by pmig** [comment]
Good point, I wasn't aware of #126. Let's not go forward on this one atm.
