### ISSUE TITLE
add progress bar and spinner in all CLI commands

### ISSUE THREAD

**Issue by tommuhm** [glasskube/glasskube#168]
the bootstrap command has nice visual effects in the terminal, it would be good to do something similar for install/uninstall comands to achiever higher consistency amongst the various commands

**Comment by kosmoz** [comment]
This is already implemented for the `install` cmd. 

To anyone interested in giving this a go, be sure to review `pkg/install/install.go` for reference before you start, so we can avoid duplicate code!

**Comment by christophenne** [comment]
related to #133 - both issues need to introduce a blocking `Uninstall` method, ideally this should only be done once.

**Comment by fykaa** [comment]
If nobody is currently working on this, would like to get assigned!

**Comment by christophenne** [comment]
@fykaa sure, go ahead :) 

As mentioned, in #133 the same blocking uninstallation will need to be used

**Comment by fykaa** [comment]
Hey @christophenne ! I'm doing well, thank you! 

I'm currently in the process of gathering all the necessary information and resources to do this effectively. I haven't started the actual work yet, but rest assured, I'll try to make a headway on it soon. I'm sorry for any hold-ups caused by this Issue, I'll keep you posted on my progress right here
