### ISSUE TITLE
Detect version mismatch between the client and `PackageOperator`

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#205]
**Is your feature request related to a problem? Please describe.**
After an update of the `glasskube` client the `PackageOperator` doesn't get updated automatically. A user must execute `glasskube bootstrap` to update the `PackageOperator`.

**Describe the solution you'd like**
Similar to #196 `glasskube` should not only detect if it wasn't already bootstrapped, but also if the `PackageOperator` matches the client version. If there is a version mismatch a message should be printed in the  after executing any cli command like:

> Glasskube `PackageOperator` needs to be updated. Please run `glasskube bootstrap` again to Glasskube from `0.0.1` (`PackageOperator` version) to `0.0.2` (client version)

**Describe alternatives you've considered**
The server component of Glasskube itself could be a glasskube package and managed via glasskube, so updating Glasskube would look like: `glasskube upgrade glasskube`

**Additional context**
This ticket can use the version util of: #254

**Comment by Baalekshan** [comment]
can I take this ?

**Comment by pmig** [comment]
yes sure

**Comment by Baalekshan** [comment]
Hi, from where can I get the packageOperator's latest image info.

**Comment by pmig** [comment]
hi @Baalekshan the client (cli) and the operator follow the same version scheme, you can have look at the client version and compare it to the packageOperator's version.

**Comment by Baalekshan** [comment]
Since the client gets updated first but the packageOperator doesn't get updated automatically, so comparing the cli's version with packageOperator solves the problem. Am I right ?

**Comment by pmig** [comment]
yes exactly

**Comment by Baalekshan** [comment]
Hey, I thought of doing this on the glasskube/cmd/checkforupdate.go but it creates a circular dependency import error (import cycle not allowed) can I just do this in separate file ? If this is okay then I will also change the existing checkforupdate.go util to clientupdate.go and newer one to packageoperatorupdate.go .

**Comment by pmig** [comment]
Hi @Baalekshan sorry for the late response yes your proposed changes sounds good to split these functionalities into two different files.

**Comment by pmig** [comment]
@Baalekshan are you still working on this issue?

**Comment by Baalekshan** [comment]
Yes I do

**Comment by christophenne** [comment]
@Baalekshan based on your question in discord about your changes in https://github.com/Baalekshan/glasskube/tree/test : You get the nil pointer dereference because the context is not yet initialized with the rest config. We have a common way to do this in all our cli commands: `SetupClientContext` in `internal/cliutils/setupclientcontext.go`. As you can see, this function is used in all commands except the `serve` command because it has special requirements. 

`SetupClientContext` contains an optional bootstrap-check (`RequireBootstrapped`), and I think inside of it, you should check whether the right version of the operator is installed – instead of inside the `root` command. If you do it in the `root` command, first of all the context is not initialized yet (which is why you get the nil pointer error), and it would also check the mismatch for commands in which it is ok to have mismatch (`version`, `serve`).

We will also need a ticket for showing the version mismatch on the UI – I will create it.

**Comment by Baalekshan** [comment]
@christophenne  So I should check for version mismatch inside of RequireBootstrapped instead of in the root command?

**Comment by christophenne** [comment]
@Baalekshan yes this is what I suggest. Might be wrong though, if you see another option feel free to try it.

**Comment by Baalekshan** [comment]
@pmig this issue can be closed now

**Comment by christophenne** [comment]
closed by https://github.com/glasskube/glasskube/pull/373
