### ISSUE TITLE
Add user feedback to packages

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#207]
**Is your feature request related to a problem? Please describe.**
Package managers like the App Store, Play Store or [Arch User Repository](https://aur.archlinux.org/) provide a possibility to comment or upvote a package.

**Describe the solution you'd like**
We could start with a discussion threads for every package on the packages repo which we then could either link to it from the website or the GUI or get these comments via the GitHub API.

**Additional context**
This is not something we would start immediately but more a ticket the will get more important in the longrun.

**Comment by kosmoz** [comment]
Maybe also giscus?

Related: https://github.com/glasskube/glasskube/issues/439

**Comment by christophenne** [comment]
Discussion page has been added in #596. 
Follow-up TODOs:
[ ] make pkg-detail-header show back button when on discussion page
[ ] show number of reactions and comments (using bootstrap icons – something like chat-left-heart and chat-left-text) instead of "Discussion" link on the package detail header
[ ] show number of reactions/comments (maybe summed up "number of interactivity") for each package on the package overview page.

**Comment by pmig** [comment]
It's already done, yes

**Comment by christophenne** [comment]
> * [ ] show number of reactions/comments (maybe summed up "number of interactivity") for each package on the package overview page

was still open, but if we need this we can create it again

**Comment by kosmoz** [comment]
> > * [ ]  show number of reactions/comments (maybe summed up "number of interactivity") for each package on the package overview page
> 
> was still open, but if we need this we can create it again

Yeah, but TBH I don't like this feature. Let's create a new issue if we decide that we want it though.
