### ISSUE TITLE
Namespace support for plain manifests

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#333]
**Is your feature request related to a problem? Please describe.**
Some applications (e.g. `argo-cd`) require [resources being applied to a specific namespace](https://argo-cd.readthedocs.io/en/stable/getting_started/#1-install-argo-cd).

**Describe the solution you'd like**
Extend `PlainManifest` with an namespace attribute. We can then even check if this namespace exists, before applying a resource. In addition we need patch objects of a `PlainManifest` with this namespace if no namespace is already present.

**Describe alternatives you've considered**
Using the `defaultNamespace` of the `PackageManifest` for all `PlainManifests`, similar to how `FluxHelmAdapter` works.

**Additional context**
ArgoCD works fine after manually patching the namespace of resources in the `reconcilePlainManifest` loop.

**Comment by kosmoz** [comment]
Thinks to consider:
* Don't overwrite the namespace property if it is set in the resource
* Priority: Resource.Namespace > PlainManifest.DefaultNamespace > PackageManifest.DefaultNamespace
* What happens if we set the namespace on a cluster scoped resource?
* Only create the default namespace if it is not included in the resources and there is at least one resource that would be created there.

**Comment by kosmoz** [comment]
We should finalize and merge https://github.com/glasskube/glasskube/pull/332 before starting to work on this.
