### ISSUE TITLE
Show and resolve version mismatch between client and operator on the UI

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#352]
**Is your feature request related to a problem? Please describe.**
We have the check in place once #205 is done, but there is no way to see it for the UI user. 

**Describe the solution you'd like**
If glasskube is bootstrapped, but the operator is in an older version, the user should get redirected to a page where they see the hint that their operator is outdated (similar to what they see on the CLI commands). Like on the regular bootstrap page, there should be a button to upgrade. 

Needs discussion about what to do with "custom" installations (i.e. slim-bootstrapped environments). 

**Describe alternatives you've considered**

**Additional context**
Related #205

**Comment by kosmoz** [comment]
An alternative to force-redirecting to a separate page would be showing an alert on the overview and details pages if the operator version is different.

IMO, this would be more similar to the UX when using the CLI, since there we don't prevent the user from interacting with the system either.

In this case we could also show a different alert if the client version is less than the operator version.
