### ISSUE TITLE
Enable logo rendering on Firefox

### ISSUE THREAD

**Issue by jakepage91** [glasskube/glasskube#482]
**Is your feature request related to a problem? Please describe.**
The logos located in the [package section](https://glasskube.dev/packages/) of the website fail to render on Firefox
![image](https://github.com/glasskube/glasskube/assets/38757612/1fe1efe0-c515-425e-8edd-500ef7066729)

It seems to fail due to the following
```
The resource at “https://pbs.twimg.com/profile_images/1092805171938234371/CeyfzQLG_400x400.jpg” was blocked because content blocking is enabled.
```
**Describe the solution you'd like**
Make sure all visual assets render on Firefox

**Additional context**
Reference: https://developer.mozilla.org/en-US/docs/Web/Privacy/Firefox_tracking_protection

**Comment by sumeshmurali** [comment]
In standard configurations of the browser this issue is not present. However, under the following scenarios the issue is present:

- You have strict tracker protection enabled
![image](https://github.com/glasskube/glasskube/assets/38063896/7e09bcf4-347c-4636-99f3-4c7c1ef1bcd3)
- Or You are viewing in private/incognito mode

So this will not be a common issue for all Firefox users.

> The resource at “https://pbs.twimg.com/profile_images/1092805171938234371/CeyfzQLG_400x400.jpg” was blocked because content blocking is enabled.

The said URL is of twitter image service and is detected as a tracker. 

#### Suggested change
May be update the URL [here](https://github.com/glasskube/glasskube/blob/9923205b1dc73832c3e026ee8b58aff9845969cf/website/src/data/packages.tsx#L91) to get the logo from GitHub should work. But the logo in the [Git](https://github.com/vmware-tanzu/velero) seems to be a bit different.

How do you want to proceed? If the above fix is good enough, I'll submit a PR

**Comment by jakepage91** [comment]
Hey there @sumeshmurali let's update the logo and use one stored on GitHub thanks, could you also make sure all other logos load correctly and make and relevant changes in your PR? Thanks

**Comment by sumeshmurali** [comment]
Sure @jakepage91, I'll start working on this. Please assign me this issue.

**Comment by sumeshmurali** [comment]
I have opened a PR for this. Please let me know if any additional changes are required.
