### ISSUE TITLE
Support repo updates with `glasskube repo update [repoName]`

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#682]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to update a `PackageRepository` custom resource via our CLI.

**Describe the solution you'd like**
There should be a `repo`-subcommand `delete`, which can be used like this:

`glasskube repo update [repositoryName]`

It should support the same flags as the `repo add` command, and additionally the `--url` flag to make changing the url possible. 

**Describe alternatives you've considered**

**Additional context**
Ref #195

**Comment by doncicuto** [comment]
Hi @christophenne, would I take this one?

**Comment by christophenne** [comment]
@doncicuto sure, go for it!

**Comment by doncicuto** [comment]
Hi @christophenne, I've prepared the changes but I'd like to confirm one doubt. In my tests I've created a couple of new repositories and played changing the url and setting a repo as the default. 

![image](https://github.com/glasskube/glasskube/assets/30386061/392f4e4a-a5f4-4825-a347-b593856e5e78)

If I change the URL, it seems to be updated in the definition for the repository but the status and message are not updated since the creation so if I had some type of error when the repo was created no matter if I update the repo url. This screenshot shows how I replaced the origin faulty test url with the glasskube repo.

![image](https://github.com/glasskube/glasskube/assets/30386061/70b5e5e4-4bd1-4232-a431-201f5dbc1fbf)

I have tried to learn more about glasskube and I guess that some kind of reconciliation must me implemented, so I'd just like to confirm that for now and for the scope of the issue I can skip that part and focus on the command update.

**Comment by christophenne** [comment]
Hi @doncicuto, have you started the operator yet? It's described here how to get started: https://github.com/glasskube/glasskube/blob/main/CONTRIBUTING.md#package-operator

> I have tried to learn more about glasskube and I guess that some kind of reconciliation must me implemented, so I'd just like to confirm that for now and for the scope of the issue I can skip that part and focus on the command update.

Exactly, that's what the operator does. It picks up the custom resources (in this case the `PackageRepository`) and applies its custom logic to it – in the case of repositories, it tries to fetch the index file and updates status and message. 

The command you are implementing doesn't have to touch the operator part, it only modifies the `PackageRepository`  custom resource to whatever the user wishes, and that's the scope of this task. Hope that clarifies your questions :)

**Comment by doncicuto** [comment]
Thanks @christophenne, perfect, then I'll skip the operator part

**Comment by doncicuto** [comment]
@christophenne some design doubts here. Let me know if you want me to change any of the following assumptions:

- If we try to update a repo and set --default, the current default repo will get the default annotation removed, and the repo to be updated will become default. If any error is found while updating the new repo a roll back for the default repo is performed. If you agree to this behavior maybe in a different issue we can change the `repo add` command so default works in the same way as right now you should get an error if there's already a default repo. 
- I added a 'none' authentication type, that will be used for the update command to set that we no longer want to use authentication with the repository

Sounds fine?

**Comment by christophenne** [comment]
@doncicuto that's a really good point, thanks for the input and creating the issue. For me your assumptions sound fine, @kosmoz are you okay with this too?
