### ISSUE TITLE
Add markdown support in package value description

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#734]
**Is your feature request related to a problem? Please describe.**
The description of a package value can be a longer text so having support for some formatting, like emphasis, links and so on would be beneficial for package authors.

**Describe the solution you'd like**
We already support markdown in the package long description, so it would be consistent to use the same markup language.

**Additional context**

Relevant template file: `internal/web/templates/components/pkg-config-input.html`

The description should be passed through the `Markdown` function.

**Comment by Baalekshan** [comment]
I'll take this @kosmoz

**Comment by christophenne** [comment]
Hi @Baalekshan , thanks for your interest!

We decided that from now on, issues with the `good first issue` label will be reserved especially for first time contributors. There will be an update about that soon in the contributing guide and on our discord too, to make it more transparent of course. 
We are glad that you are trying to contribute again, but since you have already some experience with our code base now, the other issues labeled with `help wanted` would maybe be a better fit for you. And as always, if you have your own ideas for issues that you'd like to see in glasskube, you are free to create issues here too :)

**Comment by Baalekshan** [comment]
@christophenne Yeah got it, thanks !

**Comment by rushatgabhane** [comment]
hey @christophenne, looks like this issue is still unassigned. I'd love to work on this one

**Comment by kosmoz** [comment]
Hey @rushatgabhane, how are you doing? Any progress on this one?

**Comment by rushatgabhane** [comment]
Hey yeah, I've raised a PR. Was confused why this issue was closed haha

**Comment by kosmoz** [comment]
Yeah, sorry about that, we were fiddling around with some external tooling and some issues were closed accidentally. :smile:

**Comment by kosmoz** [comment]
Could you please link your PR, I can't seem to find it…

**Comment by rushatgabhane** [comment]
Sorry I had linked it incorrectly, created a new PR - https://github.com/glasskube/glasskube/pull/974
