### ISSUE TITLE
Extend logging that happens during `serve` command

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#836]
**Is your feature request related to a problem? Please describe.**
Currently the `glasskube serve` command only logs if a user installs a package. So only following the logs it seems that the installation will not be finished.

**Describe the solution you'd like**
All (or most) status changes should be logged to `Stderr`. This can be noisy as this also might help us to reproduce and fix bugs if users can copy past us the ui logs. 

**Additional context**
This also might help investigating the "out-of-sync" task (#838).

**Comment by oversampling** [comment]
Hi, can I take this issue.

**Comment by pmig** [comment]
@christophenne what would be your recommended verbosity level?

**Comment by christophenne** [comment]
For debugging that specific issue, I use `-l 6` to see both logs from the kubernetes go client library, which is using the klog framework (e.g. when it is doing it's caching/reconnection logic etc.), and the http requests issued against the api server including the response status code.
The cache verifier that we are building right now (#911, #875) simply prints to `stderr` when it notices something unusual. I think for the out-of-sync task that should be enough logging. 

I think in the long term for logging across all commands, we should switch to a dedicated framework for doing all the logs, and make the log level parameter consistent with the log levels of the underlying libraries. This could also include writing the logs to files.

@oversampling do you have any experience with go logging, and/or would you maybe like to dive into this topic and search for some best practices, libraries, guides, etc.? This issue is not labelled "help wanted" yet, and obviously it's a bit of a bigger task. I'm fine though if you want to take the lead on this.

**Comment by oversampling** [comment]
> For debugging that specific issue, I use `-l 6` to see both logs from the kubernetes go client library, which is using the klog framework (e.g. when it is doing it's caching/reconnection logic etc.), and the http requests issued against the api server including the response status code. The cache verifier that we are building right now (#911, #875) simply prints to `stderr` when it notices something unusual. I think for the out-of-sync task that should be enough logging.
> 
> I think in the long term for logging across all commands, we should switch to a dedicated framework for doing all the logs, and make the log level parameter consistent with the log levels of the underlying libraries. This could also include writing the logs to files.
> 
> @oversampling do you have any experience with go logging, and/or would you maybe like to dive into this topic and search for some best practices, libraries, guides, etc.? This issue is not labelled "help wanted" yet, and obviously it's a bit of a bigger task. I'm fine though if you want to take the lead on this.

Hi @christophenne thanks for your feedback, really appreciate that. I will do some of the research, I try to get back to you within these two days.

**Comment by christophenne** [comment]
@jschoone thanks, good point. I created #926 because it might be a bit of a stretch for this issue here.

**Comment by christophenne** [comment]
> Hi @christophenne thanks for your feedback, really appreciate that. I will do some of the research, I try to get back to you within these two days.

Hi @oversampling, how's it going, any updates there from your side?
