### ISSUE TITLE
Repository configuration via UI frontend

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#860]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to add and update repository via the `cli`.

**Describe the solution you'd like**
When clicking on a repository a detail page should be shown (similar to `ClusterPackages`) where a user can configure the name, url and checkbox if the repo is the default repo.

Additionally there should be button to add a new repository in the top right corner.

The scope of this ticket is to create the html forms in order to send the form request to the backend.

**Additional context**
Related backend issue: https://github.com/glasskube/glasskube/issues/861
Design specification: https://glasskube.dev/docs/design/repositories/

**Comment by tanbirali** [comment]
I will like to take this

**Comment by christophenne** [comment]
@tanbirali I will write a more detailed technical design on this, since it's closely related to #861, but meanwhile you can take a closer look into our UI stack and get yourself comfortable.

**Comment by christophenne** [comment]
As promised, here's my attempt at specifying this (#860, #861) from a technical point of view:

# Requirements

* There should be a new page available via `http://localhost:8580/settings/repository/<repoName>`
* This repository configuration page should be linked to from the current settings page, for each of the listed repositories.
* The repo config page should show a html form with method `POST` and action `/settings/repository/<repoName>` (so the same as the current page, and on submit it should submit this form. 
* The form fields are: name (text), url (text), default (checkbox), where name should be disabled, and url is required. 
* There should be a Submit and a Cancel button, where the cancel button links back to the settings page. 

## Tech Design

* The endpoint needs to be registered and there should be a new http handler for that endpoint (see `server.go`)
* That endpoint handler needs to support `POST` and `GET` methods. 
* On GET, the repo config page should be rendered – this page will be a separate template `repository.html`.
* On POST, the sent form parameters should be extracted from the request, and the repository should be updated. The response of the request should be status code 200 if ok, and an error code otherwise. 

## Optional

As you might have seen, we use htmx to swap the page content. If you don't want to deal with this now, it's fine. A regular html link from the settings page to the repo page, as well as a regular form POST to the same page, are fine for now. If you are interested in htmx, you can of course try to do these dynamic page changes too (it would make sense to do a `hx-boost` link to the repo page). 

## Additional context

* The use case to add a new repo will become an extra issue and should not be handled here.

**Comment by kosmoz** [comment]
Hey @tanbirali, how are you doing? Do you need any help with this issue?

**Comment by tanbirali** [comment]
I have created a html file by the name `repository.html`with form required but I am having difficulty at registering them in the `server.go` file

**Comment by STAR-173** [comment]
Hii @tanbirali,
I am working on the Backend part of the issue. Can you open a draft PR so I could better know how to handle the data in the backend.

**Comment by christophenne** [comment]
@tanbirali what's the error/problem exactly? you will have to register the template in `templates.go`, as it's done for the other pages too.

**Comment by kosmoz** [comment]
> I have created a html file by the name `repository.html`with form required but I am having difficulty at registering them in the `server.go` file

Please raise a "draft" PR, that is the best way to allow us to assist you :slightly_smiling_face:

**Comment by tanbirali** [comment]
Yeah sure

**Comment by pmig** [comment]
solved by https://github.com/glasskube/glasskube/pull/1181
