### ISSUE TITLE
Improve Navbar on small screens

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#866]
**Is your feature request related to a problem? Please describe.**
When the UI is opened in a small browser window, the navbar/header looks like this:

![Screenshot from 2024-06-25 16-46-42](https://github.com/glasskube/glasskube/assets/7556574/b2948d33-c66e-4854-a9b8-182d597d2cf8)

**Describe the solution you'd like**
All items should stay in the same row.

**Describe alternatives you've considered**
On very small screens, it could even transform to a classical hamburger menu, but that would be an extra task.

**Comment by ParthJohri** [comment]
Greetings @christophenne, I would like to work on this issue, can you please assign it to me?

Since the web application makes use of bootstrap library, the default styles for the tags are causing this issue, my approach would be to use custom styling to bring all the items together as you suggested in the first approach. After which, I would add the stack option to bundle up all the menu items under one column and logo on the other side so that mobile version would not look clustered.

Thank you!

**Comment by christophenne** [comment]
Hi @ParthJohri, of course, thanks for taking this. If you have some questions or something to share, don't hesitate to reach out. 

Side Note: mobile is not that important for our use case, because the thing will probably be only installed on computers – but it would nevertheless be nice if it works. I'll leave that up to you if you want to do it.

**Comment by ParthJohri** [comment]
@christophenne I have made my changes and have created a [PR](https://github.com/glasskube/glasskube/pull/876) for it, please review it and let me know if I need to make any changes in the code.

To keep the changes minimal, I have not implemented the menu item dropdown in this PR, if you would like, I would create a separate PR for it.
