### ISSUE TITLE
Apps grayed out with no information / link to documentation

### ISSUE THREAD

**Issue by cdrage** [glasskube/glasskube#892]
**Describe the bug**

Docs issue?

![Screenshot 2024-06-27 at 9 11 29 AM](https://github.com/glasskube/glasskube/assets/6422176/cf7e4cd3-1d86-4319-a9f3-06b9437e98d4)

I haven't had enough coffee and I bet there are others which feel the same, but with Apps grayed out I would expect there to be a link to documentation explaining why / is it a roadmap thing / how would I be able to enable it / try it out?

**To Reproduce**

Do `glasskube serve` and try it out.

**Expected behavior**

Apps not grayed

**Screenshots**

See above / N/A.

**Cluster Info (please complete the following information):**

▶ gk version

  ____ _        _    ____ ____  _  ___   _ ____  _____
 / ___| |      / \  / ___/ ___|| |/ / | | | __ )| ____|
| |  _| |     / _ \ \___ \___ \| ' /| | | |  _ \|  _|
| |_| | |___ / ___ \ ___) |__) | . \| |_| | |_) | |___
 \____|_____/_/   \_\____/____/|_|\_\\___/|____/|_____|

glasskube: v0.11.0
package-operator: v0.11.0

**Glasskube Info (please complete the following information):**

N/A see above?

**Additional context**

N/A

**Comment by christophenne** [comment]
@cdrage thanks, we tried to tease what is coming up (apps were meant to be what the namespaced packages are now), but I guess we could have done a better job at that. 
"Apps" was just what we agreed on for v0.0.1 back in january, and then we just never changed it until yesterday where we released namespaced packages support! So that means: no more Packages/Apps, but rather ClusterPackages and Packages.
