### ISSUE TITLE
UI: Display status condition message on package details page

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#898]
**Is your feature request related to a problem? Please describe.**
If a package is in the state "installation failed" a user has no further information why the installation failed or if he should do something. Most users won't be able to look up the package status conditions.

**Describe the solution you'd like**
On the package detail page there should a message with the latest status description

**Describe alternatives you've considered**
Linking to the Kubernetes Dashboard for example (but this makes not that much sense)

**Additional context**
Related cli issue:  https://github.com/glasskube/glasskube/issues/899

**Comment by Aryakoste** [comment]
Hello @pmig @kosmoz I would like to work on this issue.

**Comment by kosmoz** [comment]
Hey @Aryakoste! Let's finish #874 first, alright?

**Comment by christophenne** [comment]
just an idea, but the status could become a "special" badge next to (or in front of) repository, installed version etc. 
if it's okay, the badge is similar to the "Installed" button now – that one would be removed. i didnt like this anyway because at that position sometimes an action is possible (open) and somtimes its status information. 
on click on that status badge, a proper popover appears and shows all details. maybe when the status is failed, there is an extra badge that shows the message directly. something like that. not a huge fan of the popover though (https://getbootstrap.com/docs/5.3/components/popovers/ )

open for discussion how to do this.

**Comment by kosmoz** [comment]
Sounds good to me. Alternative to the popover would be a tooltip: https://getbootstrap.com/docs/5.3/components/tooltips/

**Comment by christophenne** [comment]
> Sounds good to me. Alternative to the popover would be a tooltip: https://getbootstrap.com/docs/5.3/components/tooltips/

Thought about it too, but copying from a tooltip is difficult, except if we do an additional little "copy" button.

**Comment by Aryakoste** [comment]
@kosmoz Can I work on this issue. PR has been completed.

**Comment by Aryakoste** [comment]
So should I show tooltip or a popover. @kosmoz

**Comment by kosmoz** [comment]
let's start with a popover

**Comment by Aryakoste** [comment]
Hello @kosmoz @christophenne  So should i show the badge only when status failed or the badge should be shown on all status. And if so then the badge should be of danger color when Failed and normal when other statuses right. And Secondly i want to ask i have integrated the code and logic but the boostrap popover isnt working do we have to include the js bundle for popover from bootstrap or what else can we do. Below is my code of template.

<span 
          class="badge p-1 fw-normal {{ if eq .Status.Status "Failed" }}bg-danger text-white border border-1 border-danger{{ else }}bg-body-secondary text-primary-emphasis border-primary{{ end }}"
          data-bs-toggle="popover"
          data-bs-title="Status"
          data-bs-content="{{ .Status.Reason }}"
          data-bs-html="true"
          data-bs-trigger="focus"
          tabindex="0">
          Status: <strong>{{ .Status.Status }}</strong>
   </span>

**Comment by christophenne** [comment]
@Aryakoste I didn't see this when making the suggestion for popovers, but apparently it relies (or relied) on a third party js library (`popper.js`), which now seems to have been migrated to [Floating UI](https://floating-ui.com). 
I don't really like where this is going, it seems a bit too complex / too far away just to create an easy popover? It looked easier on the (now outdated) bootstrap docs. 

I think I'm rooting for a custom solution here instead of including a new library, similar to this: https://www.w3schools.com/howto/howto_css_tooltip.asp – maybe even a "regular" browser-based tooltip (with the title attribute https://www.w3schools.com/tags/att_global_title.asp) will do. If we go for this, I think there should be a little "copy" button next to it, such that the content can easily be copied into the clipboard. Alternatively, we could tease the first part of the status message and truncate it (https://getbootstrap.com/docs/5.3/helpers/text-truncation/). 

Completely different alternative: show an alert banner below the package detail header (similar to the error message banner), including the status, only if the package has status Failed. Otherwise, simply don't show the message for now. 

What do you all think about that?

**Comment by kosmoz** [comment]
I think having the status in the header makes sense, but showing the status message in an alert in case the status is failed would be a good compromise imo

**Comment by Aryakoste** [comment]
So should i show the badge of status (danger color when Failed) and only show the tooltip with message when the status is failed right. 
I will create a custom tooltip / change the styling of abbr tag to create a custom tooltip but where should i define its styling:- in the style tag, create a css file or use inline bootstrap css classess but it will be messy with this i think. @kosmoz @christophenne

**Comment by kosmoz** [comment]
I think you could also display a `<div class="alert alert-danger"></div>` showing the message below the header, instead of implementing a tooltip.

**Comment by Aryakoste** [comment]
Ok will do that. But should I keep the status badge with it or only the alert. @kosmoz

**Comment by kosmoz** [comment]
Let's keep the status badge but we don't need a tooltip/popover/..., since we have the alert as a replacement
