### ISSUE TITLE
Client settings on glasskube repo client does not update cache

### ISSUE THREAD

**Issue by jakepage91** [glasskube/glasskube#988]
**Describe the bug**
When adding/updating repo URL using the repo client `glasskube repo add <repoName> <repoURL>` The client settings cache does not update automatically (perhaps only on reconciliation) leading to the `glasskube repo list` command to show a repo URL that is not actually being fetched.

@kosmoz has identified where the logic has to be added to reset repo client cache upon adding new package repositories.  
 
**To Reproduce**

**Expected behavior**
To be able to add, delete and add a new repo URL under the same repo name and to always fetch the latest configured URL. 

**Screenshots**
![image (1)](https://github.com/glasskube/glasskube/assets/38757612/5c628827-cb39-441f-bf68-c77a742fd09e)

**Cluster Info (please complete the following information):**
 - Type: [e.g. Kubernetes, OpenShift]
 - Version: [e.g. 1.29]
 - Provider: [e.g. AWS, minikube]

**Glasskube Info (please complete the following information):**
 - Package Operator version: [e.g. v0.0.1]
 - CLI version: [output of `glasskube --version`]

**Additional context**

**Comment by ChiragRajput101** [comment]
Hi, what kind of solution would be preferred here ? 
A few files that, I think, are relevant to this issue are:
`/internal/repo/client/clientset.go`
`/internal/repo/client/defaultclient.go`
`/api/v1alpha1/packagerepository_types.go`

**Comment by kosmoz** [comment]
> Hi, what kind of solution would be preferred here ? A few files that, I think, are relevant to this issue are: `/internal/repo/client/clientset.go` `/internal/repo/client/defaultclient.go` `/api/v1alpha1/packagerepository_types.go`

This is a tough one, but I think the defaultClient would have to remember the state of the repository it handles and then the clientset needs a method that accepts a PackageRepository that updates the client for that repo. probably, a new client should be created if any part of the spec has changed. This invalidation function must be called by the ui server, as well as the package operator if a PackageRepository update is registered. 

…At least that's how I would do it. 

I think this is a pretty complex task, that's why we didn't label it as "help wanted". But if you feel like you're up to the challenge and want to give it a shot, I can assign you.

**Comment by ChiragRajput101** [comment]
Just to confirm, currently the client settings are not updated even on reconciliation?

**Comment by ChiragRajput101** [comment]
I was taking a look at: `glasskube/cmd/glasskube/cmd/repo_update.go`.
Wanted to ask what is the role of `PackageV1Alpha1Client` ( `client := cliutils.PackageClient(ctx)` ), and is it related to the defautClient that currently lacks the ability to detect changes in the repo url

**Comment by kosmoz** [comment]
> Just to confirm, currently the client settings are not updated even on reconciliation?

"Reconciliation" is a concept used by controllers/operators in the k8s cluster. The CLI typically doesn't reconcile. You can check out the reconciliation loop for the `PackageRepository` CRD in `internal/controller/packagerepository_controller.go`.

> Wanted to ask what is the role of `PackageV1Alpha1Client` ( `client := cliutils.PackageClient(ctx)` ), and is it related to the defautClient that currently lacks the ability to detect changes in the repo url

No, the two are unrelated. `PackageV1Alpha1Client` is a wrapper around the k8s api for all Glasskube CRDs. This issue is about the client that exposes the Glasskube repository to application code (see `internal/repo`)
