### ISSUE TITLE
Listen on other NIC instead of local host for `glasskube  serve`

### ISSUE THREAD

**Issue by lij55** [glasskube/glasskube#993]
I run glasskube on a remote server without UI. the default serve command listen on 127.0.0.1 only. I check the help message and could find how to change it to 0.0.0.0.

```
./glasskube  serve --help
Start server and open the UI.

Usage:
  glasskube serve [flags]

Aliases:
  serve, start, ui

Flags:
  -h, --help            help for serve
  -l, --log-level int   Level for additional logging, where 0 is the least verbose
  -p, --port int        Port for the webserver (default 8580)
  -s, --skip-open       Skip opening the browser

Global Flags:
      --kubeconfig string   Path to the kubeconfig file, whose current-context will be used (defaults to xxx.kube/config)
      --no-progress         Prevent progress logging to the cli
      --non-interactive     Run in non-interactive mode. If interactivity would be required, the command will terminate with a non-zero exit code.
      --skip-update-check   Do not check for Glasskube updates

```

**Describe the solution you'd like**

It should be able to listen on other address besdies localhost.

**Comment by christophenne** [comment]
Hi @lij55, I'm not sure if I understand `on a remote server without UI` correct. The point of the `glasskube serve` command is to run the UI, that's all it does. So I don't know if you are trying to actually run the UI server on a remote server, or if you want to have the package operator running in your cluster? 

The UI server is meant to be used locally, that's why there is no support yet for listening to something else than `localhost`. Does your use case require hosting it on a remote server, such that multiple users can use it? Then there might be other options (like every user could install glasskube), but we are also happy to discuss your use case. 

If by "without UI" you mean to just have the package operator doing its thing in your cluster, then you are done by bootstrapping glasskube in your cluster, and that's it: https://glasskube.dev/docs/getting-started/bootstrap/

**Comment by christophenne** [comment]
Oh I see, thanks for clarifying. I guess it should be ok to add an optional `--host` flag.
